server:
  port: 7999
spring:
  cloud:
    consul:
      host: ${HOST:localhost}
      port: 8500
      retry:
        max-attempts: 60
        initial-interval: 1000
        max-interval: 6000
      discovery:
        enabled: true
        register: true
        instance-id: ${spring.application.name}:${HOST:localhost}:${PORT:${server.port}}
        port: ${PORT:${server.port}}
        prefer-ip-address: true
        heartbeat:
          enabled: true
          ttl-value: 10