server:
  port: 7888
spring:
  cloud:
    consul:
      host: ${HOST:localhost}
      port: 8500
      retry:
        max-attempts: 60
        initial-interval: 1000
        max-interval: 6000
      discovery:
        enabled: true
        register: true
        instance-id: ${spring.application.name}:${HOST:localhost}:${PORT:${server.port}}
        port: ${PORT:${server.port}}
        prefer-ip-address: true
        heartbeat:
          enabled: true
          ttl-value: 10
  jackson:
    deserialization:
      ACCEPT_SINGLE_VALUE_AS_ARRAY: true
      FAIL_ON_UNKNOWN_PROPERTIES: false
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      INDENT_OUTPUT: false
    mapper:
      USE_WRAPPER_NAME_AS_PROPERTY_NAME: true
    default-property-inclusion: non_null
  freemarker:
    enabled: true
    expose-request-attributes: true
    request-context-attribute: request
  redis:
    cluster:
      nodes: 10.181.3.25:7000,10.181.3.25:7001,10.181.3.25:7002,10.181.3.26:7000,10.181.3.26:7001,10.181.3.26:7002
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 300000
  ignored-services: application,consul
  ribbon-isolation-strategy: thread
#  routes:
#    axo-mobile:
#      path: /axo-mobile/**
#      url: http://localhost:8080/
ribbon:
  ConnectTimeout: ${zuul.host.connect-timeout-millis}
  ReadTimeout: ${zuul.host.socket-timeout-millis}
  MaxTotalHttpConnections: 2000
  MaxConnectionsPerHost: 400
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
  threadpool:
    default:
      coreSize: 40
      maximumSize: 400
      allowMaximumSizeToDivergeFromCoreSize: true
ws:
  client:
    appws:
#      wsAddress: https://demowebservices.citsgbt.com/app-ws/services/appServiceRs
      wsAddress: http://10.181.10.123:8080/app-ws/services/appServiceRs
#      wsAddress: http://localhost:9090/app-ws/services/appServiceRs
      partnerId: citsamex
      userName: SHA696
      userPassword: CITSAmexSHA696
      format: json
      encrypt-password: CITSAmexSHA696
      encrypt-enabled: true
simple:
  sso:
    default-client-id: axo_mobile
    default-redirect-uri: http://localhost:8080/#!/sso
    online-sso: true
    online-sso-url: http://10.181.10.121:6080/online/index
    clients:
      - client-id: axo_mobile
        client-secret: 123456a
        grant-types: authorization_code,implicit,client_credentials,password
        redirect-uris: http://localhost:8080/#!/sso,http://10.181.57.212:7888/index.html#!/sso
swagger:
  title: AXO移动端服务接口
  description: AXO移动端服务接口,支持JSON请求和响应
  version: 1.0
  contact:
    email: gary.fu@citsgbt.com
    name: Gary Fu
  base-package: com.citsgbt.mobile.gateway
  base-path: /**
  exclude-path: /error, /ops/**